export const FINANCE_TRANSACTION_LIST_REQUEST = 'FINANCE_TRANSACTION_LIST_REQUEST';
export const FINANCE_TRANSACTION_LIST_SUCCESS = 'FINANCE_TRANSACTION_LIST_SUCCESS';
export const FINANCE_TRANSACTION_LIST_FAIL = 'FINANCE_TRANSACTION_LIST_FAIL';

export const FINANCE_TRANSACTION_DETAILS_REQUEST = 'FINANCE_TRANSACTION_DETAILS_REQUEST';
export const FINANCE_TRANSACTION_DETAILS_SUCCESS = 'FINANCE_TRANSACTION_DETAILS_SUCCESS';
export const FINANCE_TRANSACTION_DETAILS_FAIL = 'FINANCE_TRANSACTION_DETAILS_FAIL';

export const FINANCE_TRANSACTION_DELETE_REQUEST = 'FINANCE_TRANSACTION_DELETE_REQUEST';
export const FINANCE_TRANSACTION_DELETE_SUCCESS = 'FINANCE_TRANSACTION_DELETE_SUCCESS';
export const FINANCE_TRANSACTION_DELETE_FAIL = 'FINANCE_TRANSACTION_DELETE_FAIL';

export const FINANCE_TRANSACTION_CREATE_REQUEST = 'FINANCE_TRANSACTION_CREATE_REQUEST';
export const FINANCE_TRANSACTION_CREATE_SUCCESS = 'FINANCE_TRANSACTION_CREATE_SUCCESS';
export const FINANCE_TRANSACTION_CREATE_FAIL = 'FINANCE_TRANSACTION_CREATE_FAIL';
export const FINANCE_TRANSACTION_CREATE_RESET = 'FINANCE_TRANSACTION_CREATE_RESET';

export const FINANCE_TRANSACTION_UPDATE_REQUEST = 'FINANCE_TRANSACTION_UPDATE_REQUEST';
export const FINANCE_TRANSACTION_UPDATE_SUCCESS = 'FINANCE_TRANSACTION_UPDATE_SUCCESS';
export const FINANCE_TRANSACTION_UPDATE_FAIL = 'FINANCE_TRANSACTION_UPDATE_FAIL';
export const FINANCE_TRANSACTION_UPDATE_RESET = 'FINANCE_TRANSACTION_UPDATE_RESET';

export const FINANCE_REPORT_REQUEST = 'FINANCE_REPORT_REQUEST';
export const FINANCE_REPORT_SUCCESS = 'FINANCE_REPORT_SUCCESS';
export const FINANCE_REPORT_FAIL = 'FINANCE_REPORT_FAIL'; 