export const INVENTORY_TRANSACTION_LIST_REQUEST = 'INVENTORY_TRANSACTION_LIST_REQUEST';
export const INVENTORY_TRANSACTION_LIST_SUCCESS = 'INVENTORY_TRANSACTION_LIST_SUCCESS';
export const INVENTORY_TRANSACTION_LIST_FAIL = 'INVENTORY_TRANSACTION_LIST_FAIL';

export const INVENTORY_TRANSACTION_DETAILS_REQUEST = 'INVENTORY_TRANSACTION_DETAILS_REQUEST';
export const INVENTORY_TRANSACTION_DETAILS_SUCCESS = 'INVENTORY_TRANSACTION_DETAILS_SUCCESS';
export const INVENTORY_TRANSACTION_DETAILS_FAIL = 'INVENTORY_TRANSACTION_DETAILS_FAIL';

export const INVENTORY_TRANSACTION_DELETE_REQUEST = 'INVENTORY_TRANSACTION_DELETE_REQUEST';
export const INVENTORY_TRANSACTION_DELETE_SUCCESS = 'INVENTORY_TRANSACTION_DELETE_SUCCESS';
export const INVENTORY_TRANSACTION_DELETE_FAIL = 'INVENTORY_TRANSACTION_DELETE_FAIL';

export const INVENTORY_TRANSACTION_CREATE_REQUEST = 'INVENTORY_TRANSACTION_CREATE_REQUEST';
export const INVENTORY_TRANSACTION_CREATE_SUCCESS = 'INVENTORY_TRANSACTION_CREATE_SUCCESS';
export const INVENTORY_TRANSACTION_CREATE_FAIL = 'INVENTORY_TRANSACTION_CREATE_FAIL';
export const INVENTORY_TRANSACTION_CREATE_RESET = 'INVENTORY_TRANSACTION_CREATE_RESET';

export const INVENTORY_TRANSACTION_UPDATE_REQUEST = 'INVENTORY_TRANSACTION_UPDATE_REQUEST';
export const INVENTORY_TRANSACTION_UPDATE_SUCCESS = 'INVENTORY_TRANSACTION_UPDATE_SUCCESS';
export const INVENTORY_TRANSACTION_UPDATE_FAIL = 'INVENTORY_TRANSACTION_UPDATE_FAIL';
export const INVENTORY_TRANSACTION_UPDATE_RESET = 'INVENTORY_TRANSACTION_UPDATE_RESET';

export const INVENTORY_STOCK_REQUEST = 'INVENTORY_STOCK_REQUEST';
export const INVENTORY_STOCK_SUCCESS = 'INVENTORY_STOCK_SUCCESS';
export const INVENTORY_STOCK_FAIL = 'INVENTORY_STOCK_FAIL';

export const INVENTORY_REPORT_REQUEST = 'INVENTORY_REPORT_REQUEST';
export const INVENTORY_REPORT_SUCCESS = 'INVENTORY_REPORT_SUCCESS';
export const INVENTORY_REPORT_FAIL = 'INVENTORY_REPORT_FAIL';

export const PRODUCT_COST_UPDATE_REQUEST = 'PRODUCT_COST_UPDATE_REQUEST';
export const PRODUCT_COST_UPDATE_SUCCESS = 'PRODUCT_COST_UPDATE_SUCCESS';
export const PRODUCT_COST_UPDATE_FAIL = 'PRODUCT_COST_UPDATE_FAIL';
export const PRODUCT_COST_UPDATE_RESET = 'PRODUCT_COST_UPDATE_RESET'; 